package com.hemebiotech.analytics;

import java.util.Map;

/**
 * Write symptom data from a source using the writeSymptoms method.
 */

public interface ISymptomWriter {

	/**
	 * this method takes the Map generated by the method in
	 * ReadSymptomDataFromFile.java as input and writes to the output file
	 * 
	 * @param a map of symptoms
	 */
	public void writeSymptoms(Map<String, Integer> symptoms);
}
